export { RegisterPage } from './pages/register-page'
export { LoginPage } from './pages/login-page'
export { OtpVerificationPage } from './pages/otp-verification-page'
export { ForgotPasswordPage } from './pages/forgot-password-page'
export { ResetPasswordPage } from './pages/reset-password-page'
export { ChangePasswordPage } from './pages/change-password-page'
export { OAuthCallbackPage } from './pages/oauth-callback-page'
